#!/bin/bash
if [ ! -d $OPENSHIFT_DATA_DIR/uploads ]; then
    mkdir $OPENSHIFT_DATA_DIR/uploads
fi
ln -sf $OPENSHIFT_DATA_DIR/uploads $OPENSHIFT_REPO_DIR/php/wp-content/
ln -sf $OPENSHIFT_DATA_DIR/wp-config.php $OPENSHIFT_REPO_DIR/php/wp-config.php
ln -sf $OPENSHIFT_DATA_DIR/.htaccess $OPENSHIFT_REPO_DIR/php/.htaccess